### ISSUE TITLE
commit b771577bd7124cd5f725b5a375d3160396ef61f3 breaks the use of unregistered TLDs

### ISSUE THREAD

**Issue by samthesamman** [celzero/firestack#92]
For my home network, I run my own DNS and use TLD internal (eg: I can access my server at http://server.internal). The 'internal' keyword was recently reserved for private use (https://serverfault.com/questions/17255/top-level-domain-domain-suffix-for-private-network).

However, in commit b771577bd7124cd5f725b5a375d3160396ef61f3 (mark undelegated subdomains with "." prefix), when I use RethinkDNS and set up a simple wireguard config, my DNS can no longer resolve any domains *.internal (same with *.home, or *.loc, etc etc).

**Comment by ignoramous** [comment]
Since that commit, Rethink redirects "local" (undelegated) domains to *System DNS* only when *Configure* -> *DNS* -> *Prevent DNS leaks* is turned ON, as it considers resolving these domains via remote DNS resolvers "a leak". Perhaps, we must add a separate setting (*Prefer System DNS for undelegated domains*) to let users control this behaviour.

**Comment by ignoramous** [comment]
> Perhaps, we must add a separate setting (Prefer System DNS for undelegated domains) to let users control this behaviour.

A new setting will be made available in `v055o` (the next version, which is due in a few days) to let end-users prefer non-System DNS for [ALL undelegated domains](https://github.com/celzero/firestack/blob/4e46456525/intra/dnsx/undelegated.go).
